#! /bin/sh

sxhkd &

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144.0 --output eDP-1-1 --mode 1920x1080 --rate 144.0 --right-of HDMI-0

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8
bspc monitor eDP-1-1 -d 9 0

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#launching polybar 
/home/rvk7895/.scripts/launch_polybar.sh

bspc config top_padding 22

feh --bg-fill ~/ricing_stuff/PinkNord/.wallpapers/pink-nord-theme/cyber-sword-2.png

bspc rule -a Zathura state=tiled
