#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-1-0 --primary --mode 1920x1080 --rate 144.00 --right-of eDP-1 --mode 1920x1080 --rate 144.00

bspc monitor HDMI-1-0 -d 3 4 5 6 7 8 9 0
bspc monitor eDP-1 -d 1 2

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		 22

#wallpaper 
nitrogen --restore &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM configuration ####
_bc window_gap			  8
_bc top_padding			  50
_bc top_monocle_padding		  0
_bc border_width 		  2
_bc bottom_padding 		  0
_bc left_padding 		  0
_bc right_padding 		  0
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle  	  true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus 		  true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc merge_overlapping_monitors    true
_bc pointer_follows_monitor 	  true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
bspc config active_border_color "#474f54"
bspc config focused_border_color "#474f54"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

dunst &
sxhkd &
picom --experimental-backends &

~/.config/bspwm/autostart &
